language: python
python:
  - "pypy3"
  - "3.7"
  - "3.8"
  - "nightly"
# command to install dependencies
install:
  - "pip install ."
  - "pip install coveralls"
# command to run tests
script:
  nosetests  --with-coverage --cover-package=datasize
# command to run on successful builds
after_success:
  coveralls
